// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jJfin9zcBmewTDUBq0KamHx-VED9yzo',
    appId: '1:772008717866:web:b73885853095452f179d53',
    messagingSenderId: '772008717866',
    projectId: 'siparistakipdemo',
    authDomain: 'siparistakipdemo.firebaseapp.com',
    storageBucket: 'siparistakipdemo.appspot.com',
    measurementId: 'G-N1KYKE9F1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByM1rS447eCMJb-53zvgDH8kQi5mdDRto',
    appId: '1:772008717866:android:6486552f9dab49c5179d53',
    messagingSenderId: '772008717866',
    projectId: 'siparistakipdemo',
    storageBucket: 'siparistakipdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNAzf5RdDqt7tmk13OEaD1rnExpAWFdtI',
    appId: '1:772008717866:ios:2069a64a8a5c18ef179d53',
    messagingSenderId: '772008717866',
    projectId: 'siparistakipdemo',
    storageBucket: 'siparistakipdemo.appspot.com',
    iosClientId: '772008717866-t5uthb88biusjrcq6ct49hj1ijugf17j.apps.googleusercontent.com',
    iosBundleId: 'com.example.siparisTakipDemo',
  );
}
